[package]
name = "fishrs"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
mappy = { git = "https://github.com/fishrs/mappy", version = "0.1.0" }
rppal = "0.18.0"
serde_json = "1.0.120"
unda = "0.2.2"
